feat: develop form directive
worktile/store pull request #120
Opened 2023-06-12 09:19 UTC by 791045873

参考ngxs实现了form.directive。
目前directive支持对store和表单的双向绑定。支持复杂路径。支持在store中resetForm。
在store中构建form相关内容时，应使用提供的工具方法thyFormModel。

2023-06-13 00:38 UTC, 791045873 commented
该指令只处理了formGroup，如果想简单的绑定在formControl上，还需要再开发。

2023-06-13 06:56 UTC, why520crazy requested changes

2023-06-13 06:56 UTC, why520crazy commented on packages/store/form/form-store.ts
> +export function thyFormModel<T>(
这个函数建议命名为 `createFormModelState` 或者 `createFormModel` ，thyFormModel 函数看意思不知道是做什么的

2023-06-13 06:56 UTC, why520crazy commented on packages/store/form/form.directive.ts
> +    @Input() path: string;
组件参数命名建议加上前缀 thy,  这个 path 改为 `thyStatePath` 吧

2023-06-13 06:56 UTC, why520crazy commented on packages/store/form/form.directive.ts
> +    @Input() clearDestroy = false
这个也是一样，改为 `thyClearOnDestroy` 同时建议默认为 true，组件销毁清除数据比较好

2023-06-13 06:56 UTC, why520crazy commented on packages/store/form/form.utils.ts
> +export const getValue = (obj: any, prop: string): any =>
store 类库依赖了 `@tethys/cdk` 对于对象类型的设置和获取值，`@tethys/cdk/immutable`  已经提供了 produce 函数处理类似的需求，可以直接使用

```ts
import { produce } from '@tethys/cdk/immutable';
produce({ user: { name: 'peter' } }).set('user.name', 'new');
produce({ user: { name: 'peter' } }).get('user.name');
```

2023-06-13 06:56 UTC, why520crazy commented on packages/store/form/form.directive.ts
> +                        obj = setValue(obj, `${this.path}.dirty`, this.form.dirty)
这里换成 produce 的时候可以一起设置，无需单独设置三次

2023-06-13 06:56 UTC, why520crazy commented on packages/store/store.ts
> +    public resetForm$ = new Subject<{ path: string, value?: any }>()
这里的 Store 应该是单纯的数据操作，不应该有 Form 相关的流，建议去掉 resetForm

即使要提供和 Form 相关的函数，那应该是在 FormStore 中添加。

2023-06-14 08:14 UTC, 791045873 commented on packages/store/form/form.directive.ts
> +                        obj = setValue(obj, `${this.path}.dirty`, this.form.dirty)
produce(state).set(path, value)好像不支持链式调用，也不支持批量设置。还是得set好几次

2023-06-14 08:44 UTC, 791045873 commented on packages/store/store.ts
> +    public resetForm$ = new Subject<{ path: string, value?: any }>()
可以，先去掉resetForm。之后在开发FormStore的时候再完善相关功能

2023-06-19 01:27 UTC, 791045873 commented on packages/store/form/form.directive.ts
> +                        obj = setValue(obj, `${this.path}.dirty`, this.form.dirty)
@why520crazy

2023-06-21 06:26 UTC, why520crazy requested changes

2023-06-21 06:26 UTC, why520crazy commented on packages/store/form/form.directive.ts
> +    @Input() clearDestroy = true
clearDestroy 以及 dynamic 和 debounce 等 Input 参数都需要加 thy 前缀

2023-06-28 06:13 UTC, why520crazy approved these changes

2023-06-28 06:13 UTC, merged

2023-06-28 06:50 UTC, why520crazy commented on packages/store/form/form.directive.ts
> +                        obj = setValue(obj, `${this.path}.dirty`, this.form.dirty)
我所得不是链式调用，而是：
```
produce(state).set(this.path, {
  model: this.form.getRawValue(),
  status: this.form.status,
  dirty: this.form.dirty
})
```

2023-06-28 06:59 UTC, 791045873 commented on packages/store/form/form.directive.ts
> +                        obj = setValue(obj, `${this.path}.dirty`, this.form.dirty)
ok