feat: active entity$ support trigger by update entity
worktile/store pull request #125
Opened 2023-07-28 09:51 UTC by Guoxiin

2023-07-28 10:45 UTC, why520crazy requested changes

2023-07-28 10:45 UTC, why520crazy commented on packages/store/test/entity-store.spec.ts
> +                    expect(entity).toEqual({ _id: '1', name: 'task 1' });
你这里的断言有问题，如果 setActive 并没有触发 activeEntity$ 的订阅，这个测试也会通过，最好应该在 setActive 前就订阅 activeEntity$，然后获取到值是初始化的，之后设置完后断言触发了 activeEntity$，设置了新的对象，然后此时再次订阅一次获取到最新的对象。

2023-07-28 10:45 UTC, why520crazy commented on packages/store/entity-store.ts
>          shareReplay()
严格的说应该需要加 `shareReplay(1)`

2023-07-31 02:29 UTC, Guoxiin commented on packages/store/test/entity-store.spec.ts
> +                    expect(entity).toEqual({ _id: '1', name: 'task 1' });
我每个 tasksEntityStore 都是独立的，没 setActive ，不会触发 activeEntity$。我加了个在 setActive 前就订阅 activeEntity$，预期是 null，更明确一些

2023-08-15 09:48 UTC, why520crazy requested changes

2023-08-15 09:48 UTC, why520crazy commented on packages/store/test/entity-store.spec.ts
> +                    expect(entity).toEqual({ _id: '1', name: 'task 1' });
我的意思你那个 subscribe 里面加的断言有可能永远不会被执行，那么测试也是通过的。

如果你期望订阅的时候会有一次那么需要 subscribe 后把变量保存一下，然后代码中断言，类似
```ts
const firstEntity: TaskInfo;
tasksEntityStore.activeEntity$.pipe(first()).subscribe((entity) => {
                   firstEntity = entity;
 });
expect(firstEntity).toEqual(null);
```

2023-09-18 03:07 UTC, why520crazy requested changes

2023-09-18 03:07 UTC, why520crazy commented on packages/store/test/entity-store.spec.ts
> +                });
这个代码最好把 tasksEntityStore.setActive('1'); 放在外层执行，这样看上去更加清晰一些
```ts
let activeEntity: TaskInfo;
 tasksEntityStore.activeEntity$.subscribe((entity) => {
         activeEntity = entity;
});
expect(activeEntity).toEqual(null);
tasksEntityStore.setActive('1');
expect(activeEntity).toEqual({ _id: '1', name: 'task 1' });
// 订阅的时候已经存在 active 的场景
let activeEntityAfterSubscribe: TaskInfo;
tasksEntityStore.activeEntity$.subscribe((entity) => {
       activeEntityAfterSubscribe = entity;
 });
expect(activeEntityAfterSubscribe).toEqual({ _id: '1', name: 'task 1' });
tasksEntityStore.setActive('not-found-id');
expect(activeEntity).toEqual(null);
```

2023-09-18 03:07 UTC, why520crazy commented on packages/store/test/entity-store.spec.ts
> +                tasksEntityStore.activeEntity$.pipe(first()).subscribe((entity) => {
测试代码如上个示例

2023-09-19 01:47 UTC, why520crazy approved these changes

2023-09-19 01:48 UTC, merged