feat: entityStore support active
worktile/store pull request #77
Opened 2022-11-09 05:37 UTC by Guoxiin

2022-11-09 06:26 UTC, why520crazy requested changes

2022-11-09 06:26 UTC, why520crazy commented on packages/store/src/entity-store.ts
> +
要不 EntityState 默认就继承 ActiveState 吧，或者去掉 ActiveState 在 EntityState 加上 activeId? 和 activeEntity?
现在接口分开了，但是 EntityStore 的类型却需要用到，也没有完全解耦，但使用成本却增加了。

2022-11-09 06:26 UTC, why520crazy commented on packages/store/src/store/examples/todos/todos.component.ts
> +        });
建议不要在 Todos 的示例上加 Active 的功能，独立一个示例或者不写示例，另外就是示例最好直接在版本中使用 store.activeId 或者 store.activeId$

2022-11-09 06:26 UTC, why520crazy commented on packages/store/src/entity-store.ts
> +    });
这个 activeEntity 直接通过 activeId 获取是否可以？这样就不用加一个 activeEntity 状态了？

2022-11-09 06:28 UTC, Guoxiin commented on packages/store/src/entity-store.ts
> +
是的，我也发现这个问题了，我看下处理下

2022-11-09 06:29 UTC, Guoxiin commented on packages/store/src/store/examples/todos/todos.component.ts
> +        });
我新加一个示例

2022-11-09 06:34 UTC, Guoxiin commented on packages/store/src/entity-store.ts
> +    });
可以的

2022-11-10 05:49 UTC, why520crazy requested changes

2022-11-10 05:49 UTC, why520crazy commented on packages/store/src/entity-store.ts
> +    );
这里加一个 shareReply 管道，多次订阅的时候只执行一次

2022-11-10 05:49 UTC, why520crazy commented on packages/store/src/entity-store.ts
> +        const entity = this.snapshot.entities.filter((entity) => {
这个用 find 不就可以了，为啥要用 filter 后再取第0个？

2022-11-10 06:34 UTC, why520crazy approved these changes

2022-11-10 06:34 UTC, merged